/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ietf-interfaces.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

#ifndef _IETF_INTERFACES_H_
#define _IETF_INTERFACES_H_

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef if__ns
#define if__ns 1700122010
#define if__ns_id "urn:ietf:params:xml:ns:yang:ietf-interfaces"
#define if__ns_uri "urn:ietf:params:xml:ns:yang:ietf-interfaces"
#endif

#define if_down 2
#define if_lower_layer_down 7
#define if_out_multicast_pkts 723352241
#define if_link_up_down_trap_enable 1552886723
#define if_name 1998270519
#define if_description 202559156
#define if_in_broadcast_pkts 1140019954
#define if_in_octets 1354763654
#define if_out_discards 2051284211
#define if_not_present 6
#define if_speed 1423237997
#define if_higher_layer_if 750793054
#define if_in_unknown_protos 1961345832
#define if_disabled 2
#define if_lower_layer_if 247228720
#define if_if_index 216876767
#define if_interface_type 1566485963
#define if_in_unicast_pkts 1100444555
#define if_interface 221572658
#define if_phys_address 1102597279
#define if_in_multicast_pkts 1126031588
#define if_last_change 2008341778
#define if_interfaces_state 2120054373
#define if_testing 3
#define if_out_broadcast_pkts 1427076806
#define if_in_errors 419802148
#define if_type 2040883914
#define if_statistics 1049034618
#define if_up 1
#define if_in_discards 1607867097
#define if_out_errors 1825475719
#define if_dormant 5
#define if_admin_status 2104862928
#define if_out_unicast_pkts 170730703
#define if_oper_status 1906453952
#define if_discontinuity_time 318342031
#define if_out_octets 2123582464
#define if_unknown 4
#define if_interfaces 321503962

#ifdef __cplusplus
}
#endif

#endif
