/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ietf-yang-types.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

#ifndef _IETF_YANG_TYPES_H_
#define _IETF_YANG_TYPES_H_

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef yang__ns
#define yang__ns 1567598639
#define yang__ns_id "urn:ietf:params:xml:ns:yang:ietf-yang-types"
#define yang__ns_uri "urn:ietf:params:xml:ns:yang:ietf-yang-types"
#endif


#ifdef __cplusplus
}
#endif

#endif
