/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: openconfig-inet-types.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

#ifndef _OPENCONFIG_INET_TYPES_H_
#define _OPENCONFIG_INET_TYPES_H_

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef oc_inet__ns
#define oc_inet__ns 1386743137
#define oc_inet__ns_id "http://openconfig.net/yang/types/inet"
#define oc_inet__ns_uri "http://openconfig.net/yang/types/inet"
#endif

#define oc_inet_IPV4 4
#define oc_inet_UNKNOWN 0
#define oc_inet_IPV6 6

#ifdef __cplusplus
}
#endif

#endif
