/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: openconfig-terminal-device.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

#ifndef _OPENCONFIG_TERMINAL_DEVICE_H_
#define _OPENCONFIG_TERMINAL_DEVICE_H_

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef oc_opt_term__ns
#define oc_opt_term__ns 201815720
#define oc_opt_term__ns_id "http://openconfig.net/yang/terminal-device"
#define oc_opt_term__ns_uri "http://openconfig.net/yang/terminal-device"
#endif

#define oc_opt_term_physical_channel 1994537587
#define oc_opt_term_polarization_mode_dispersion 1665158511
#define oc_opt_term_DISABLED 1
#define oc_opt_term_mode_id 2141263764
#define oc_opt_term_errored_seconds 2042646331
#define oc_opt_term_ingress 1440811799
#define oc_opt_term_in_8021q_frames 1930482994
#define oc_opt_term_mode 575893728
#define oc_opt_term_transceiver 170005784
#define oc_opt_term_interval 559952988
#define oc_opt_term_terminal_device 1412921500
#define oc_opt_term_operational_mode 745082763
#define oc_opt_term_OPTICAL_CHANNEL 1
#define oc_opt_term_in_mac_control_frames 1842676927
#define oc_opt_term_code_violations 1380694212
#define oc_opt_term_admin_state 1519849494
#define oc_opt_term_description 202559156
#define oc_opt_term_target_output_power 1907745428
#define oc_opt_term_unavailable_seconds 1337652464
#define oc_opt_term_q_value 251351784
#define oc_opt_term_second_order_polarization_mode_dispersion 1037367250
#define oc_opt_term_ethernet 766975154
#define oc_opt_term_logical_channel_assignments 827152208
#define oc_opt_term_MAINT 2
#define oc_opt_term_tti_msg_recv 121097439
#define oc_opt_term_in_jabber_frames 408306399
#define oc_opt_term_rdi_msg 416929895
#define oc_opt_term_max 2088175689
#define oc_opt_term_in_crc_errors 621329595
#define oc_opt_term_avg 2050512522
#define oc_opt_term_LOGICAL_CHANNEL 0
#define oc_opt_term_allocation 1779434013
#define oc_opt_term_fec_corrected_bits 1755603872
#define oc_opt_term_config 2105663071
#define oc_opt_term_fec_uncorrectable_words 1222725929
#define oc_opt_term_DOWN 1
#define oc_opt_term_tti_msg_transmit 613276322
#define oc_opt_term_pre_fec_ber 930828535
#define oc_opt_term_out_mac_pause_frames 1294592065
#define oc_opt_term_laser_bias_current 1521732466
#define oc_opt_term_loopback_mode 2918605
#define oc_opt_term_post_fec_ber 1498085913
#define oc_opt_term_UP 0
#define oc_opt_term_severely_errored_seconds 1149956064
#define oc_opt_term_in_fragment_frames 564635238
#define oc_opt_term_link_state 702349774
#define oc_opt_term_state 630973766
#define oc_opt_term_background_block_errors 873216247
#define oc_opt_term_group_id 2095068827
#define oc_opt_term_otn 432742433
#define oc_opt_term_tti_msg_auto 683355091
#define oc_opt_term_instant 2051543381
#define oc_opt_term_output_power 571387945
#define oc_opt_term_operational_modes 837791618
#define oc_opt_term_index 827593980
#define oc_opt_term_chromatic_dispersion 1778860338
#define oc_opt_term_assignment 2116271785
#define oc_opt_term_test_signal 1511903072
#define oc_opt_term_rate_class 1823938197
#define oc_opt_term_logical_channel_type 1859345210
#define oc_opt_term_NONE 0
#define oc_opt_term_logical_channel 1356112295
#define oc_opt_term_input_power 1019491846
#define oc_opt_term_esnr 1872423537
#define oc_opt_term_in_mac_pause_frames 1003418322
#define oc_opt_term_frequency 1225884603
#define oc_opt_term_assignment_type 1368992484
#define oc_opt_term_min 83205090
#define oc_opt_term_FACILITY 1
#define oc_opt_term_polarization_dependent_loss 1526260636
#define oc_opt_term_trib_protocol 788023075
#define oc_opt_term_ENABLED 0
#define oc_opt_term_vendor_id 1357446
#define oc_opt_term_channel 1372178362
#define oc_opt_term_line_port 1480436606
#define oc_opt_term_out_8021q_frames 1916377746
#define oc_opt_term_TERMINAL 2
#define oc_opt_term_optical_channel 949559623
#define oc_opt_term_in_oversize_frames 1638462268
#define oc_opt_term_out_mac_control_frames 1033076598
#define oc_opt_term_logical_channels 1237135909
#define oc_opt_term_fec_corrected_bytes 1141619065
#define oc_opt_term_tti_msg_expected 371937930

#ifdef __cplusplus
}
#endif

#endif
