/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: openconfig-types.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

#ifndef _OPENCONFIG_TYPES_H_
#define _OPENCONFIG_TYPES_H_

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef oc_types__ns
#define oc_types__ns 1708343055
#define oc_types__ns_id "http://openconfig.net/yang/openconfig-types"
#define oc_types__ns_uri "http://openconfig.net/yang/openconfig-types"
#endif

#define oc_types_ADDRESS_FAMILY 2015099501
#define oc_types_IPV4 2050433468
#define oc_types_L2_ETHERNET 1415666213
#define oc_types_IPV6 1468531886
#define oc_types_MPLS 2067937967

#ifdef __cplusplus
}
#endif

#endif
