/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: openconfig-interfaces.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

#ifndef _OPENCONFIG_INTERFACES_H_
#define _OPENCONFIG_INTERFACES_H_

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef oc_if__ns
#define oc_if__ns 131460205
#define oc_if__ns_id "http://openconfig.net/yang/interfaces"
#define oc_if__ns_uri "http://openconfig.net/yang/interfaces"
#endif

#define oc_if_down 940209651
#define oc_if_NOT_PRESENT 6
#define oc_if_subinterface 1294223328
#define oc_if_hold_time 204730640
#define oc_if_out_multicast_pkts 723352241
#define oc_if_name 1998270519
#define oc_if_UNKNOWN 4
#define oc_if_LOWER_LAYER_DOWN 7
#define oc_if_description 202559156
#define oc_if_in_broadcast_pkts 1140019954
#define oc_if_enabled 197426095
#define oc_if_in_octets 1354763654
#define oc_if_out_discards 2051284211
#define oc_if_DORMANT 5
#define oc_if_mtu 1751455506
#define oc_if_in_unknown_protos 1961345832
#define oc_if_config 2105663071
#define oc_if_loopback_mode 2918605
#define oc_if_in_unicast_pkts 1100444555
#define oc_if_last_clear 1168907511
#define oc_if_interface 221572658
#define oc_if_state 630973766
#define oc_if_in_multicast_pkts 1126031588
#define oc_if_last_change 2008341778
#define oc_if_in_fcs_errors 422454373
#define oc_if_index 827593980
#define oc_if_ifindex 1259815303
#define oc_if_out_broadcast_pkts 1427076806
#define oc_if_carrier_transitions 1056552358
#define oc_if_in_errors 419802148
#define oc_if_type 2040883914
#define oc_if_up 1984149991
#define oc_if_in_discards 1607867097
#define oc_if_out_errors 1825475719
#define oc_if_admin_status 2104862928
#define oc_if_out_unicast_pkts 170730703
#define oc_if_oper_status 1906453952
#define oc_if_counters 1327053922
#define oc_if_out_octets 2123582464
#define oc_if_subinterfaces 1730428758
#define oc_if_interfaces 321503962

#ifdef __cplusplus
}
#endif

#endif
