/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: openconfig-alarm-types.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

#ifndef _OPENCONFIG_ALARM_TYPES_H_
#define _OPENCONFIG_ALARM_TYPES_H_

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef oc_alarm_types__ns
#define oc_alarm_types__ns 1488383119
#define oc_alarm_types__ns_id "http://openconfig.net/yang/alarms/types"
#define oc_alarm_types__ns_uri "http://openconfig.net/yang/alarms/types"
#endif

#define oc_alarm_types_UNKNOWN 250589858
#define oc_alarm_types_CRITICAL 1041805575
#define oc_alarm_types_LOS 1450931068
#define oc_alarm_types_WARNING 777626720
#define oc_alarm_types_AIS 1126475851
#define oc_alarm_types_OTS 1914508559
#define oc_alarm_types_OPENCONFIG_ALARM_SEVERITY 1386825255
#define oc_alarm_types_MAJOR 2136641963
#define oc_alarm_types_MINOR 1480452853
#define oc_alarm_types_OPENCONFIG_ALARM_TYPE_ID 1379778926
#define oc_alarm_types_EQPT 1258233442

#ifdef __cplusplus
}
#endif

#endif
