/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: openconfig-transport-types.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

#ifndef _OPENCONFIG_TRANSPORT_TYPES_H_
#define _OPENCONFIG_TRANSPORT_TYPES_H_

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef oc_opt_types__ns
#define oc_opt_types__ns 650858634
#define oc_opt_types__ns_id "http://openconfig.net/yang/transport-types"
#define oc_opt_types__ns_uri "http://openconfig.net/yang/transport-types"
#endif

#define oc_opt_types_ETH_100G_ACC 294639208
#define oc_opt_types_TRIB_RATE_400G 303426306
#define oc_opt_types_DISABLED 1
#define oc_opt_types_CFP2_ACO 1993896118
#define oc_opt_types_TRIB_RATE_200G 1256630225
#define oc_opt_types_ETH_40GBASE_LR4 1601857436
#define oc_opt_types_PROT_OC768 377812028
#define oc_opt_types_SONET_APPLICATION_CODE 235150170
#define oc_opt_types_TRIB_RATE_1G 964471180
#define oc_opt_types_MPO_CONNECTOR 35336415
#define oc_opt_types_PROT_OC192 639857513
#define oc_opt_types_VSR2000_3R3 1515631259
#define oc_opt_types_ETH_10GBASE_ER 1154077682
#define oc_opt_types_OPTICAL_CHANNEL 841008882
#define oc_opt_types_CFP 1662591652
#define oc_opt_types_ETH_100GBASE_CLR4 1767593404
#define oc_opt_types_OTN_UNDEFINED 2126858449
#define oc_opt_types_NON_PLUGGABLE 906545694
#define oc_opt_types_LC_CONNECTOR 823593939
#define oc_opt_types_MAINT 2
#define oc_opt_types_PROT_STM16 1295957807
#define oc_opt_types_ETH_100GBASE_ER4 1928089435
#define oc_opt_types_PROT_ODU2 1139046106
#define oc_opt_types_PROT_40GE 87166250
#define oc_opt_types_VSR2000_3R2 1541938324
#define oc_opt_types_ETH_UNDEFINED 670713374
#define oc_opt_types_PROT_1GE 314984941
#define oc_opt_types_FIBER_CONNECTOR_TYPE 866061901
#define oc_opt_types_PROT_10GE_WAN 837221192
#define oc_opt_types_ETH_100GBASE_PSM4 351232461
#define oc_opt_types_ETH_100GBASE_SR10 1857743567
#define oc_opt_types_PROT_10GE_LAN 939019145
#define oc_opt_types_P1L1_2D1 1264912413
#define oc_opt_types_PROT_OC48 2134887122
#define oc_opt_types_ETH_40GBASE_PSM4 436266353
#define oc_opt_types_ETH_10GBASE_ZR 291222403
#define oc_opt_types_PROT_OTU3 1067695530
#define oc_opt_types_ETH_100GBASE_LR4 662256057
#define oc_opt_types_OTHER 187383631
#define oc_opt_types_PROT_ODU4 464770018
#define oc_opt_types_ETH_100GBASE_CWDM4 1136660261
#define oc_opt_types_QSFP28 163346280
#define oc_opt_types_PROT_100GE 840412440
#define oc_opt_types_SFP_PLUS 1800189527
#define oc_opt_types_XFP 99528716
#define oc_opt_types_TRIB_RATE_10G 491143765
#define oc_opt_types_QSFP_PLUS 1154257832
#define oc_opt_types_PROT_OTU2E 550226405
#define oc_opt_types_ETH_10GBASE_LR 1930684140
#define oc_opt_types_ETH_10GBASE_SR 1278195833
#define oc_opt_types_PROT_STM256 857630476
#define oc_opt_types_PROT_OTN 2140624747
#define oc_opt_types_LOGICAL_ELEMENT_PROTOCOL_TYPE 1984949741
#define oc_opt_types_ETH_4X10GBASE_SR 1714559344
#define oc_opt_types_PROT_OTU2 870921151
#define oc_opt_types_PROT_OTU4 1676386528
#define oc_opt_types_SFP 473383033
#define oc_opt_types_PROT_ETHERNET 1340894587
#define oc_opt_types_ETH_40GBASE_ER4 839649076
#define oc_opt_types_CFP4 971805626
#define oc_opt_types_TRIB_RATE_20x2e5G 351766558
#define oc_opt_types_VSR2000_3R5 1684913663
#define oc_opt_types_PROT_OTUCN 750092840
#define oc_opt_types_NONE 0
#define oc_opt_types_ETH_4X10GBASE_LR 1777114288
#define oc_opt_types_TRIB_RATE_40G 1796959629
#define oc_opt_types_TRIB_RATE_150G 1691208783
#define oc_opt_types_PROT_STM64 955814975
#define oc_opt_types_TRIB_RATE_100G 362515952
#define oc_opt_types_TRIBUTARY_PROTOCOL_TYPE 1160819312
#define oc_opt_types_OTN_APPLICATION_CODE 1554026035
#define oc_opt_types_QSFP 1362283707
#define oc_opt_types_ETH_10GBASE_LRM 682078196
#define oc_opt_types_ETH_40GBASE_SR4 959283248
#define oc_opt_types_ETH_100GBASE_SR4 1353397010
#define oc_opt_types_PROT_ODUCN 320705337
#define oc_opt_types_PROT_ODU3 488834512
#define oc_opt_types_TRIB_RATE_300G 1905429729
#define oc_opt_types_FACILITY 1
#define oc_opt_types_CPAK 1910620157
#define oc_opt_types_PROT_100G_MLG 1568725416
#define oc_opt_types_ETH_40GBASE_CR4 476907487
#define oc_opt_types_X2 275841849
#define oc_opt_types_ETH_100G_AOC 2005820788
#define oc_opt_types_ENABLED 0
#define oc_opt_types_P1S1_2D2 541209553
#define oc_opt_types_ETH_100GBASE_CR4 1654663619
#define oc_opt_types_PROT_OTU1E 1067906708
#define oc_opt_types_TRIB_RATE_250G 1101731374
#define oc_opt_types_TRANSCEIVER_FORM_FACTOR_TYPE 1235980173
#define oc_opt_types_SONET_UNDEFINED 517044495
#define oc_opt_types_CFP2 148492385
#define oc_opt_types_PROT_ODU2E 1499860341
#define oc_opt_types_TERMINAL 2
#define oc_opt_types_TRIBUTARY_RATE_CLASS_TYPE 2108031500
#define oc_opt_types_ETHERNET_PMD_TYPE 777924563
#define oc_opt_types_SC_CONNECTOR 486788081
#define oc_opt_types_P1L1_2D2 493858731

#ifdef __cplusplus
}
#endif

#endif
