/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: openconfig-platform-transceiver.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

#ifndef _OPENCONFIG_PLATFORM_TRANSCEIVER_H_
#define _OPENCONFIG_PLATFORM_TRANSCEIVER_H_

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef oc_transceiver__ns
#define oc_transceiver__ns 585067544
#define oc_transceiver__ns_id "http://openconfig.net/yang/platform/transceiver"
#define oc_transceiver__ns_uri "http://openconfig.net/yang/platform/transceiver"
#endif

#define oc_transceiver_internal_temp 1419004070
#define oc_transceiver_NOT_PRESENT 1
#define oc_transceiver_otn_compliance_code 2068647721
#define oc_transceiver_fault_condition 1122095305
#define oc_transceiver_transceiver 170005784
#define oc_transceiver_output_frequency 884786563
#define oc_transceiver_interval 559952988
#define oc_transceiver_description 202559156
#define oc_transceiver_target_output_power 1907745428
#define oc_transceiver_tx_laser 1159284595
#define oc_transceiver_enabled 197426095
#define oc_transceiver_max 2088175689
#define oc_transceiver_avg 2050512522
#define oc_transceiver_PRESENT 0
#define oc_transceiver_config 2105663071
#define oc_transceiver_ethernet_pmd 1853114659
#define oc_transceiver_laser_bias_current 1521732466
#define oc_transceiver_state 630973766
#define oc_transceiver_ethernet_pmd_preconf 781770860
#define oc_transceiver_physical_channels 634498055
#define oc_transceiver_instant 2051543381
#define oc_transceiver_serial_no 480270650
#define oc_transceiver_output_power 571387945
#define oc_transceiver_index 827593980
#define oc_transceiver_vendor_rev 533031606
#define oc_transceiver_connector_type 1855142630
#define oc_transceiver_input_power 1019491846
#define oc_transceiver_date_code 1902762841
#define oc_transceiver_sonet_sdh_compliance_code 425947975
#define oc_transceiver_form_factor_preconf 673112044
#define oc_transceiver_vendor_part 708944586
#define oc_transceiver_min 83205090
#define oc_transceiver_channel 1372178362
#define oc_transceiver_form_factor 605079377
#define oc_transceiver_vendor 1639541835
#define oc_transceiver_present 2043219423

#ifdef __cplusplus
}
#endif

#endif
