/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: openconfig-telemetry-types.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

#ifndef _OPENCONFIG_TELEMETRY_TYPES_H_
#define _OPENCONFIG_TELEMETRY_TYPES_H_

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef oc_telemetry_types__ns
#define oc_telemetry_types__ns 35186107
#define oc_telemetry_types__ns_id "http://openconfig.net/yang/telemetry-types"
#define oc_telemetry_types__ns_uri "http://openconfig.net/yang/telemetry-types"
#endif

#define oc_telemetry_types_ENC_JSON_IETF 810803199
#define oc_telemetry_types_ENC_PROTO3 679227105
#define oc_telemetry_types_STREAM_WEBSOCKET_RPC 891393615
#define oc_telemetry_types_STREAM_GRPC 442300132
#define oc_telemetry_types_ENC_XML 1958722388
#define oc_telemetry_types_STREAM_THRIFT_RPC 2066710899
#define oc_telemetry_types_STREAM_SSH 1748818774
#define oc_telemetry_types_DATA_ENCODING_METHOD 864500188
#define oc_telemetry_types_STREAM_JSON_RPC 412762089
#define oc_telemetry_types_STREAM_PROTOCOL 1998828232

#ifdef __cplusplus
}
#endif

#endif
