/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: openconfig-platform-types.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

#ifndef _OPENCONFIG_PLATFORM_TYPES_H_
#define _OPENCONFIG_PLATFORM_TYPES_H_

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef oc_platform_types__ns
#define oc_platform_types__ns 1014513867
#define oc_platform_types__ns_id "http://openconfig.net/yang/platform-types"
#define oc_platform_types__ns_uri "http://openconfig.net/yang/platform-types"
#endif

#define oc_platform_types_OPENCONFIG_SOFTWARE_COMPONENT 1157725893
#define oc_platform_types_LINECARD 1977515942
#define oc_platform_types_CPU 2003850434
#define oc_platform_types_DISABLED 1464461520
#define oc_platform_types_FAN 1369376826
#define oc_platform_types_INTEGRATED_CIRCUIT 423035511
#define oc_platform_types_OPERATING_SYSTEM 588501281
#define oc_platform_types_SENSOR 325116750
#define oc_platform_types_POWER_DISABLED 1
#define oc_platform_types_BACKPLANE 516734991
#define oc_platform_types_INACTIVE 1100742089
#define oc_platform_types_OPENCONFIG_HARDWARE_COMPONENT 751182229
#define oc_platform_types_TRANSCEIVER 985296955
#define oc_platform_types_POWER_ENABLED 0
#define oc_platform_types_PORT 1557878253
#define oc_platform_types_ACTIVE 1776322622
#define oc_platform_types_FRU 164729260
#define oc_platform_types_POWER_SUPPLY 1365464960
#define oc_platform_types_COMPONENT_OPER_STATUS 1122930247
#define oc_platform_types_CHASSIS 1020895844
#define oc_platform_types_STORAGE 1440738496
#define oc_platform_types_FABRIC 551652471

#ifdef __cplusplus
}
#endif

#endif
