/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: openconfig-telemetry.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

#ifndef _OPENCONFIG_TELEMETRY_H_
#define _OPENCONFIG_TELEMETRY_H_

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef oc_telemetry__ns
#define oc_telemetry__ns 927750072
#define oc_telemetry__ns_id "http://openconfig.net/yang/telemetry"
#define oc_telemetry__ns_uri "http://openconfig.net/yang/telemetry"
#endif

#define oc_telemetry_destination_group 1598383525
#define oc_telemetry_heartbeat_interval 1281304246
#define oc_telemetry_path 1002915403
#define oc_telemetry_persistent_subscriptions 1211207143
#define oc_telemetry_sensor_group 521692491
#define oc_telemetry_exclude_filter 1205417205
#define oc_telemetry_name 1998270519
#define oc_telemetry_sample_interval 1730479987
#define oc_telemetry_sensor_paths 1692117363
#define oc_telemetry_sensor_path 424127023
#define oc_telemetry_destination 1426812369
#define oc_telemetry_protocol 943257313
#define oc_telemetry_destination_groups 676110724
#define oc_telemetry_config 2105663071
#define oc_telemetry_sensor_profiles 2055311817
#define oc_telemetry_state 630973766
#define oc_telemetry_destination_address 1799113401
#define oc_telemetry_group_id 2095068827
#define oc_telemetry_encoding 180862443
#define oc_telemetry_sensor_group_id 1378386708
#define oc_telemetry_sensor_groups 1378032050
#define oc_telemetry_sensor_profile 1970107157
#define oc_telemetry_destinations 1001041063
#define oc_telemetry_telemetry_system 658036610
#define oc_telemetry_suppress_redundant 1367205526
#define oc_telemetry_destination_port 1685436757
#define oc_telemetry_local_source_address 1348732713
#define oc_telemetry_dynamic_subscriptions 358197336
#define oc_telemetry_id 1279252765
#define oc_telemetry_subscriptions 886823438
#define oc_telemetry_dynamic_subscription 1460307865
#define oc_telemetry_originated_qos_marking 324407343
#define oc_telemetry_persistent_subscription 1373683679

#ifdef __cplusplus
}
#endif

#endif
