/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: openconfig-yang-types.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

#ifndef _OPENCONFIG_YANG_TYPES_H_
#define _OPENCONFIG_YANG_TYPES_H_

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef oc_yang__ns
#define oc_yang__ns 1603982894
#define oc_yang__ns_id "http://openconfig.net/yang/types/yang"
#define oc_yang__ns_uri "http://openconfig.net/yang/types/yang"
#endif


#ifdef __cplusplus
}
#endif

#endif
