/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: openconfig-if-ethernet.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

#ifndef _OPENCONFIG_IF_ETHERNET_H_
#define _OPENCONFIG_IF_ETHERNET_H_

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef oc_eth__ns
#define oc_eth__ns 1857063266
#define oc_eth__ns_id "http://openconfig.net/yang/interfaces/ethernet"
#define oc_eth__ns_uri "http://openconfig.net/yang/interfaces/ethernet"
#endif

#define oc_eth_SPEED_40GB 1431070194
#define oc_eth_in_8021q_frames 1930482994
#define oc_eth_in_mac_control_frames 1842676927
#define oc_eth_ethernet 766975154
#define oc_eth_in_jabber_frames 408306399
#define oc_eth_in_crc_errors 621329595
#define oc_eth_SPEED_100GB 1977203562
#define oc_eth_SPEED_UNKNOWN 1980508219
#define oc_eth_config 2105663071
#define oc_eth_out_mac_pause_frames 1294592065
#define oc_eth_in_fragment_frames 564635238
#define oc_eth_state 630973766
#define oc_eth_HALF 1
#define oc_eth_ETHERNET_SPEED 1987059756
#define oc_eth_SPEED_1GB 1894348501
#define oc_eth_auto_negotiate 2102272149
#define oc_eth_SPEED_25GB 1898852688
#define oc_eth_SPEED_50GB 1290536247
#define oc_eth_in_mac_pause_frames 1003418322
#define oc_eth_SPEED_10GB 620120484
#define oc_eth_SPEED_100MB 1591127439
#define oc_eth_FULL 0
#define oc_eth_counters 1327053922
#define oc_eth_port_speed 1659992901
#define oc_eth_negotiated_port_speed 1543346698
#define oc_eth_SPEED_10MB 699501289
#define oc_eth_hw_mac_address 761716137
#define oc_eth_negotiated_duplex_mode 1452772647
#define oc_eth_enable_flow_control 204818831
#define oc_eth_out_8021q_frames 1916377746
#define oc_eth_duplex_mode 1404309190
#define oc_eth_mac_address 2110689796
#define oc_eth_in_oversize_frames 1638462268
#define oc_eth_out_mac_control_frames 1033076598

#ifdef __cplusplus
}
#endif

#endif
