/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: openconfig-platform.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

#ifndef _OPENCONFIG_PLATFORM_H_
#define _OPENCONFIG_PLATFORM_H_

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef oc_platform__ns
#define oc_platform__ns 748738173
#define oc_platform__ns_id "http://openconfig.net/yang/platform"
#define oc_platform__ns_uri "http://openconfig.net/yang/platform"
#endif

#define oc_platform_firmware_version 1588326193
#define oc_platform_cpu 1825182739
#define oc_platform_memory 1156186237
#define oc_platform_interval 559952988
#define oc_platform_name 1998270519
#define oc_platform_temperature 362670904
#define oc_platform_description 202559156
#define oc_platform_part_no 1487153423
#define oc_platform_max 2088175689
#define oc_platform_fabric 76530483
#define oc_platform_avg 2050512522
#define oc_platform_power_supply 1094968203
#define oc_platform_mfg_name 1230757718
#define oc_platform_subcomponent 410071270
#define oc_platform_config 2105663071
#define oc_platform_integrated_circuit 658274749
#define oc_platform_alarm_severity 1871511136
#define oc_platform_allocated_power 781373945
#define oc_platform_alarm_threshold 27572169
#define oc_platform_utilized 2041312965
#define oc_platform_state 630973766
#define oc_platform_POWER_DISABLED 1
#define oc_platform_configurable 1116873706
#define oc_platform_hardware_version 475247789
#define oc_platform_port 10387472
#define oc_platform_instant 2051543381
#define oc_platform_serial_no 480270650
#define oc_platform_alarm_status 1979041785
#define oc_platform_POWER_ENABLED 0
#define oc_platform_components 962606743
#define oc_platform_software_version 909128828
#define oc_platform_properties 1953873399
#define oc_platform_type 2040883914
#define oc_platform_property 1802560321
#define oc_platform_used_power 844379205
#define oc_platform_subcomponents 1378797355
#define oc_platform_component 1543026623
#define oc_platform_id 1279252765
#define oc_platform_available 162386130
#define oc_platform_chassis 247732213
#define oc_platform_min 83205090
#define oc_platform_fan 1957768428
#define oc_platform_oper_status 1906453952
#define oc_platform_backplane 1637824912
#define oc_platform_storage 452237353
#define oc_platform_value 864367181

#ifdef __cplusplus
}
#endif

#endif
