/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: system-information.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

#ifndef _SYSTEM_INFORMATION_H_
#define _SYSTEM_INFORMATION_H_

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef si__ns
#define si__ns 1073449819
#define si__ns_id "http://sssup.it/system-information"
#define si__ns_uri "http://sssup.it/system-information"
#endif

#define si_name 1998270519
#define si_package_information 2538459
#define si_product_name 243134770
#define si_software 568560098
#define si_system_information 1462028137
#define si_host_name 1476961893
#define si_serial_number 544353266
#define si_comment 452863039
#define si_vendor 1639541835

#ifdef __cplusplus
}
#endif

#endif
